// Generated by regenerate_wavelength_references.py. Do not edit.
#pragma once

#include "diffraction_reference_oracle.h"

#include <array>
#include <string_view>

namespace diffractionmaterial::validation
{
inline constexpr double kFiniteSceneReferenceStepNanometres = 5;
inline constexpr double kFiniteSceneMaximumZeroClampedLinearSrgbChannelError
    = 0.15;

struct WavelengthValidationScene
{
    std::string_view name;
    Description description;
    reference::EvaluationInput input;
    std::array<double, 3> expectedZeroClampedLinearSrgb;
};

inline const std::array<WavelengthValidationScene, 5>& wavelengthValidationScenes()
{
    static const auto scenes = [] {
        std::array<WavelengthValidationScene, 5> result {};
        {
            Description description {};
            description.version = 5;
            description.geometry.directionUv = { 1.0f, 0.0f };
            description.geometry.grooveSpacingNanometres = 1000.0f;
            description.geometry.lattice = GratingLattice::OneDimensional;
            description.geometry.secondaryDirectionUv = { 0.0f, 0.0f };
            description.geometry.secondaryGrooveSpacingNanometres = 0.0f;
            description.grooveField.mode = GrooveFieldMode::Constant;
            description.grooveField.originUv = { 0.0f, 0.0f };
            description.grooveField.axisUv = { 0.0f, 0.0f };
            description.grooveField.grooveSpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.secondarySpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.orientationDegreesPerUnit = 0.0f;
            description.microstructure = { GrooveProfile::BinaryRectangular, 125.0f, 0.5f, 0.0f };
            description.substrate = { 0.17f, 3.1f };
            description.coating = { CoatingModel::Uncoated, 0.0f, { 0.0f, 0.0f } };
            description.roughness = { 0.0f, 0.08f };
            description.spectrum.integrationModel = SpectralIntegrationModel::Cie1931Xyz;
            description.spectrum.wavelengthCount = 8;
            description.spectrum.wavelengthsNanometres = { 380.0f, 420.0f, 460.0f, 500.0f, 540.0f, 580.0f, 640.0f, 700.0f };
            description.spectrum.firstOrder = 1;
            description.spectrum.lastOrder = 4;
            reference::EvaluationInput input {};
            input.incidentDirection = { 0, 0, 1 };
            input.materialUv = { 0.5, 0.5 };
            input.incidentSpectrum = { 1, 1, 1, 1, 1, 1, 1, 1 };
            result[0] = { "aluminium-binary-preset", description, input,
                { 0.676881912469, 0.583821077414, 0.649560715142 } };
        }
        {
            Description description {};
            description.version = 5;
            description.geometry.directionUv = { 1.0f, 0.0f };
            description.geometry.grooveSpacingNanometres = 1000.0f;
            description.geometry.lattice = GratingLattice::OneDimensional;
            description.geometry.secondaryDirectionUv = { 0.0f, 0.0f };
            description.geometry.secondaryGrooveSpacingNanometres = 0.0f;
            description.grooveField.mode = GrooveFieldMode::Constant;
            description.grooveField.originUv = { 0.0f, 0.0f };
            description.grooveField.axisUv = { 0.0f, 0.0f };
            description.grooveField.grooveSpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.secondarySpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.orientationDegreesPerUnit = 0.0f;
            description.microstructure = { GrooveProfile::Sinusoidal, 180.0f, 0.5f, 0.0f };
            description.substrate = { 0.17f, 3.1f };
            description.coating = { CoatingModel::Uncoated, 0.0f, { 0.0f, 0.0f } };
            description.roughness = { 6.0f, 0.04f };
            description.spectrum.integrationModel = SpectralIntegrationModel::Cie1931Xyz;
            description.spectrum.wavelengthCount = 8;
            description.spectrum.wavelengthsNanometres = { 380.0f, 420.0f, 460.0f, 500.0f, 540.0f, 580.0f, 640.0f, 700.0f };
            description.spectrum.firstOrder = 1;
            description.spectrum.lastOrder = 4;
            reference::EvaluationInput input {};
            input.incidentDirection = { 0, 0, 1 };
            input.materialUv = { 0.5, 0.5 };
            input.incidentSpectrum = { 1, 1, 1, 1, 1, 1, 1, 1 };
            result[1] = { "sinusoidal-preset", description, input,
                { 0.701870423673, 0.519974682472, 0.476876090550 } };
        }
        {
            Description description {};
            description.version = 5;
            description.geometry.directionUv = { 1.0f, 0.0f };
            description.geometry.grooveSpacingNanometres = 1000.0f;
            description.geometry.lattice = GratingLattice::OneDimensional;
            description.geometry.secondaryDirectionUv = { 0.0f, 0.0f };
            description.geometry.secondaryGrooveSpacingNanometres = 0.0f;
            description.grooveField.mode = GrooveFieldMode::Constant;
            description.grooveField.originUv = { 0.0f, 0.0f };
            description.grooveField.axisUv = { 0.0f, 0.0f };
            description.grooveField.grooveSpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.secondarySpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.orientationDegreesPerUnit = 0.0f;
            description.microstructure = { GrooveProfile::BlazedSawtooth, 250.0f, 1.0f, 14.036243f };
            description.substrate = { 0.17f, 3.1f };
            description.coating = { CoatingModel::IncoherentDielectric, 1000.0f, { 1.5f, 0.001f } };
            description.roughness = { 2.0f, 0.02f };
            description.spectrum.integrationModel = SpectralIntegrationModel::Cie1931Xyz;
            description.spectrum.wavelengthCount = 8;
            description.spectrum.wavelengthsNanometres = { 380.0f, 420.0f, 460.0f, 500.0f, 540.0f, 580.0f, 640.0f, 700.0f };
            description.spectrum.firstOrder = 1;
            description.spectrum.lastOrder = 4;
            reference::EvaluationInput input {};
            input.incidentDirection = { 0, 0, 1 };
            input.materialUv = { 0.5, 0.5 };
            input.incidentSpectrum = { 1, 1, 1, 1, 1, 1, 1, 1 };
            result[2] = { "blazed-coated-preset", description, input,
                { 0.678992092297, 0.657931355960, 0.720017596322 } };
        }
        {
            Description description {};
            description.version = 5;
            description.geometry.directionUv = { 1.0f, 0.0f };
            description.geometry.grooveSpacingNanometres = 1000.0f;
            description.geometry.lattice = GratingLattice::CrossedTwoDimensional;
            description.geometry.secondaryDirectionUv = { 0.0f, 1.0f };
            description.geometry.secondaryGrooveSpacingNanometres = 1400.0f;
            description.grooveField.mode = GrooveFieldMode::Constant;
            description.grooveField.originUv = { 0.0f, 0.0f };
            description.grooveField.axisUv = { 0.0f, 0.0f };
            description.grooveField.grooveSpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.secondarySpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.orientationDegreesPerUnit = 0.0f;
            description.microstructure = { GrooveProfile::BinaryRectangular, 125.0f, 0.5f, 0.0f };
            description.substrate = { 0.17f, 3.1f };
            description.coating = { CoatingModel::Uncoated, 0.0f, { 0.0f, 0.0f } };
            description.roughness = { 0.0f, 0.08f };
            description.spectrum.integrationModel = SpectralIntegrationModel::Cie1931Xyz;
            description.spectrum.wavelengthCount = 8;
            description.spectrum.wavelengthsNanometres = { 380.0f, 420.0f, 460.0f, 500.0f, 540.0f, 580.0f, 640.0f, 700.0f };
            description.spectrum.firstOrder = 1;
            description.spectrum.lastOrder = 4;
            reference::EvaluationInput input {};
            input.incidentDirection = { 0, 0, 1 };
            input.materialUv = { 0.5, 0.5 };
            input.incidentSpectrum = { 1, 1, 1, 1, 1, 1, 1, 1 };
            result[3] = { "crossed-binary-preset", description, input,
                { 0.467680512279, 0.409494272436, 0.496628099609 } };
        }
        {
            Description description {};
            description.version = 5;
            description.geometry.directionUv = { 1.0f, 0.0f };
            description.geometry.grooveSpacingNanometres = 10000.0f;
            description.geometry.lattice = GratingLattice::OneDimensional;
            description.geometry.secondaryDirectionUv = { 0.0f, 0.0f };
            description.geometry.secondaryGrooveSpacingNanometres = 0.0f;
            description.grooveField.mode = GrooveFieldMode::Constant;
            description.grooveField.originUv = { 0.0f, 0.0f };
            description.grooveField.axisUv = { 0.0f, 0.0f };
            description.grooveField.grooveSpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.secondarySpacingDeltaNanometresPerUnit = 0.0f;
            description.grooveField.orientationDegreesPerUnit = 0.0f;
            description.microstructure = { GrooveProfile::Sinusoidal, 180.0f, 0.5f, 0.0f };
            description.substrate = { 0.17f, 3.1f };
            description.coating = { CoatingModel::Uncoated, 0.0f, { 0.0f, 0.0f } };
            description.roughness = { 0.0f, 0.0f };
            description.spectrum.integrationModel = SpectralIntegrationModel::Cie1931Xyz;
            description.spectrum.wavelengthCount = 8;
            description.spectrum.wavelengthsNanometres = { 380.0f, 420.0f, 460.0f, 500.0f, 540.0f, 580.0f, 640.0f, 700.0f };
            description.spectrum.firstOrder = 1;
            description.spectrum.lastOrder = 8;
            reference::EvaluationInput input {};
            input.incidentDirection = { 0, 0, 1 };
            input.materialUv = { 0.5, 0.5 };
            input.incidentSpectrum = { 1, 1, 1, 1, 1, 1, 1, 1 };
            result[4] = { "sinusoidal-order-eight", description, input,
                { 1.119717517638, 0.884932427684, 0.847356361070 } };
        }
        return result;
    }();
    return scenes;
}
} // namespace diffractionmaterial::validation
